// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bczwhiyiuxtkwlfeqnik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjendoaXlpdXh0a3dsZmVxbmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTE5MzEsImV4cCI6MjA2MjE2NzkzMX0.t1vYwMMt14C8MGu0oey0N379doyswn3hr8woP_n39jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);